// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  CommunityOpenCashDrawer dco_decode_box_autoadd_community_open_cash_drawer(
    dynamic raw,
  );

  @protected
  GotiginCatalogMenuImageSelection
  dco_decode_box_autoadd_gotigin_catalog_menu_image_selection(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  CommunityAuditEventView dco_decode_community_audit_event_view(dynamic raw);

  @protected
  CommunityAuditTimeline dco_decode_community_audit_timeline(dynamic raw);

  @protected
  CommunityBackupResult dco_decode_community_backup_result(dynamic raw);

  @protected
  CommunityCartLine dco_decode_community_cart_line(dynamic raw);

  @protected
  CommunityCashDrawerResult dco_decode_community_cash_drawer_result(
    dynamic raw,
  );

  @protected
  CommunityCategoryView dco_decode_community_category_view(dynamic raw);

  @protected
  CommunityCustomerView dco_decode_community_customer_view(dynamic raw);

  @protected
  CommunityDiagnosticEventView dco_decode_community_diagnostic_event_view(
    dynamic raw,
  );

  @protected
  CommunityDiagnosticsPack dco_decode_community_diagnostics_pack(dynamic raw);

  @protected
  CommunityDiagnosticsShareResult dco_decode_community_diagnostics_share_result(
    dynamic raw,
  );

  @protected
  CommunityDiagnosticsWorkspace dco_decode_community_diagnostics_workspace(
    dynamic raw,
  );

  @protected
  CommunityDraftOrderResult dco_decode_community_draft_order_result(
    dynamic raw,
  );

  @protected
  CommunityDraftOrderView dco_decode_community_draft_order_view(dynamic raw);

  @protected
  CommunityExpenseView dco_decode_community_expense_view(dynamic raw);

  @protected
  CommunityExpensesWorkspace dco_decode_community_expenses_workspace(
    dynamic raw,
  );

  @protected
  CommunityFinancialCsvExport dco_decode_community_financial_csv_export(
    dynamic raw,
  );

  @protected
  CommunityInventoryItemView dco_decode_community_inventory_item_view(
    dynamic raw,
  );

  @protected
  CommunityInventoryWorkspace dco_decode_community_inventory_workspace(
    dynamic raw,
  );

  @protected
  CommunityInvoiceDetail dco_decode_community_invoice_detail(dynamic raw);

  @protected
  CommunityInvoiceLineView dco_decode_community_invoice_line_view(dynamic raw);

  @protected
  CommunityInvoicePaymentView dco_decode_community_invoice_payment_view(
    dynamic raw,
  );

  @protected
  CommunityInvoiceView dco_decode_community_invoice_view(dynamic raw);

  @protected
  CommunityItemSalesView dco_decode_community_item_sales_view(dynamic raw);

  @protected
  CommunityKitchenTicketLineView dco_decode_community_kitchen_ticket_line_view(
    dynamic raw,
  );

  @protected
  CommunityKitchenTicketView dco_decode_community_kitchen_ticket_view(
    dynamic raw,
  );

  @protected
  CommunityModifierOptionView dco_decode_community_modifier_option_view(
    dynamic raw,
  );

  @protected
  CommunityOpenCashDrawer dco_decode_community_open_cash_drawer(dynamic raw);

  @protected
  CommunityPaymentAllocation dco_decode_community_payment_allocation(
    dynamic raw,
  );

  @protected
  CommunityProductView dco_decode_community_product_view(dynamic raw);

  @protected
  CommunitySalePricingPreview dco_decode_community_sale_pricing_preview(
    dynamic raw,
  );

  @protected
  CommunitySaleResult dco_decode_community_sale_result(dynamic raw);

  @protected
  CommunitySalesSummary dco_decode_community_sales_summary(dynamic raw);

  @protected
  CommunityStaffSecurity dco_decode_community_staff_security(dynamic raw);

  @protected
  CommunityStaffView dco_decode_community_staff_view(dynamic raw);

  @protected
  CommunitySyncQueue dco_decode_community_sync_queue(dynamic raw);

  @protected
  CommunitySyncQueueItemView dco_decode_community_sync_queue_item_view(
    dynamic raw,
  );

  @protected
  CommunityTaxRateView dco_decode_community_tax_rate_view(dynamic raw);

  @protected
  CommunityTaxRateWorkspace dco_decode_community_tax_rate_workspace(
    dynamic raw,
  );

  @protected
  CommunityWorkspace dco_decode_community_workspace(dynamic raw);

  @protected
  GotiginCatalogMenuImageSelection
  dco_decode_gotigin_catalog_menu_image_selection(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<CommunityAuditEventView> dco_decode_list_community_audit_event_view(
    dynamic raw,
  );

  @protected
  List<CommunityCartLine> dco_decode_list_community_cart_line(dynamic raw);

  @protected
  List<CommunityCategoryView> dco_decode_list_community_category_view(
    dynamic raw,
  );

  @protected
  List<CommunityCustomerView> dco_decode_list_community_customer_view(
    dynamic raw,
  );

  @protected
  List<CommunityDiagnosticEventView>
  dco_decode_list_community_diagnostic_event_view(dynamic raw);

  @protected
  List<CommunityDraftOrderView> dco_decode_list_community_draft_order_view(
    dynamic raw,
  );

  @protected
  List<CommunityExpenseView> dco_decode_list_community_expense_view(
    dynamic raw,
  );

  @protected
  List<CommunityInventoryItemView>
  dco_decode_list_community_inventory_item_view(dynamic raw);

  @protected
  List<CommunityInvoiceLineView> dco_decode_list_community_invoice_line_view(
    dynamic raw,
  );

  @protected
  List<CommunityInvoicePaymentView>
  dco_decode_list_community_invoice_payment_view(dynamic raw);

  @protected
  List<CommunityInvoiceView> dco_decode_list_community_invoice_view(
    dynamic raw,
  );

  @protected
  List<CommunityItemSalesView> dco_decode_list_community_item_sales_view(
    dynamic raw,
  );

  @protected
  List<CommunityKitchenTicketLineView>
  dco_decode_list_community_kitchen_ticket_line_view(dynamic raw);

  @protected
  List<CommunityKitchenTicketView>
  dco_decode_list_community_kitchen_ticket_view(dynamic raw);

  @protected
  List<CommunityModifierOptionView>
  dco_decode_list_community_modifier_option_view(dynamic raw);

  @protected
  List<CommunityPaymentAllocation> dco_decode_list_community_payment_allocation(
    dynamic raw,
  );

  @protected
  List<CommunityProductView> dco_decode_list_community_product_view(
    dynamic raw,
  );

  @protected
  List<CommunityStaffView> dco_decode_list_community_staff_view(dynamic raw);

  @protected
  List<CommunitySyncQueueItemView>
  dco_decode_list_community_sync_queue_item_view(dynamic raw);

  @protected
  List<CommunityTaxRateView> dco_decode_list_community_tax_rate_view(
    dynamic raw,
  );

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  CommunityOpenCashDrawer?
  dco_decode_opt_box_autoadd_community_open_cash_drawer(dynamic raw);

  @protected
  GotiginCatalogMenuImageSelection?
  dco_decode_opt_box_autoadd_gotigin_catalog_menu_image_selection(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  List<CommunityPaymentAllocation>?
  dco_decode_opt_list_community_payment_allocation(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  CommunityOpenCashDrawer sse_decode_box_autoadd_community_open_cash_drawer(
    SseDeserializer deserializer,
  );

  @protected
  GotiginCatalogMenuImageSelection
  sse_decode_box_autoadd_gotigin_catalog_menu_image_selection(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  CommunityAuditEventView sse_decode_community_audit_event_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityAuditTimeline sse_decode_community_audit_timeline(
    SseDeserializer deserializer,
  );

  @protected
  CommunityBackupResult sse_decode_community_backup_result(
    SseDeserializer deserializer,
  );

  @protected
  CommunityCartLine sse_decode_community_cart_line(
    SseDeserializer deserializer,
  );

  @protected
  CommunityCashDrawerResult sse_decode_community_cash_drawer_result(
    SseDeserializer deserializer,
  );

  @protected
  CommunityCategoryView sse_decode_community_category_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityCustomerView sse_decode_community_customer_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDiagnosticEventView sse_decode_community_diagnostic_event_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDiagnosticsPack sse_decode_community_diagnostics_pack(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDiagnosticsShareResult sse_decode_community_diagnostics_share_result(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDiagnosticsWorkspace sse_decode_community_diagnostics_workspace(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDraftOrderResult sse_decode_community_draft_order_result(
    SseDeserializer deserializer,
  );

  @protected
  CommunityDraftOrderView sse_decode_community_draft_order_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityExpenseView sse_decode_community_expense_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityExpensesWorkspace sse_decode_community_expenses_workspace(
    SseDeserializer deserializer,
  );

  @protected
  CommunityFinancialCsvExport sse_decode_community_financial_csv_export(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInventoryItemView sse_decode_community_inventory_item_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInventoryWorkspace sse_decode_community_inventory_workspace(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInvoiceDetail sse_decode_community_invoice_detail(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInvoiceLineView sse_decode_community_invoice_line_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInvoicePaymentView sse_decode_community_invoice_payment_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityInvoiceView sse_decode_community_invoice_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityItemSalesView sse_decode_community_item_sales_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityKitchenTicketLineView sse_decode_community_kitchen_ticket_line_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityKitchenTicketView sse_decode_community_kitchen_ticket_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityModifierOptionView sse_decode_community_modifier_option_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityOpenCashDrawer sse_decode_community_open_cash_drawer(
    SseDeserializer deserializer,
  );

  @protected
  CommunityPaymentAllocation sse_decode_community_payment_allocation(
    SseDeserializer deserializer,
  );

  @protected
  CommunityProductView sse_decode_community_product_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunitySalePricingPreview sse_decode_community_sale_pricing_preview(
    SseDeserializer deserializer,
  );

  @protected
  CommunitySaleResult sse_decode_community_sale_result(
    SseDeserializer deserializer,
  );

  @protected
  CommunitySalesSummary sse_decode_community_sales_summary(
    SseDeserializer deserializer,
  );

  @protected
  CommunityStaffSecurity sse_decode_community_staff_security(
    SseDeserializer deserializer,
  );

  @protected
  CommunityStaffView sse_decode_community_staff_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunitySyncQueue sse_decode_community_sync_queue(
    SseDeserializer deserializer,
  );

  @protected
  CommunitySyncQueueItemView sse_decode_community_sync_queue_item_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityTaxRateView sse_decode_community_tax_rate_view(
    SseDeserializer deserializer,
  );

  @protected
  CommunityTaxRateWorkspace sse_decode_community_tax_rate_workspace(
    SseDeserializer deserializer,
  );

  @protected
  CommunityWorkspace sse_decode_community_workspace(
    SseDeserializer deserializer,
  );

  @protected
  GotiginCatalogMenuImageSelection
  sse_decode_gotigin_catalog_menu_image_selection(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<CommunityAuditEventView> sse_decode_list_community_audit_event_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityCartLine> sse_decode_list_community_cart_line(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityCategoryView> sse_decode_list_community_category_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityCustomerView> sse_decode_list_community_customer_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityDiagnosticEventView>
  sse_decode_list_community_diagnostic_event_view(SseDeserializer deserializer);

  @protected
  List<CommunityDraftOrderView> sse_decode_list_community_draft_order_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityExpenseView> sse_decode_list_community_expense_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityInventoryItemView>
  sse_decode_list_community_inventory_item_view(SseDeserializer deserializer);

  @protected
  List<CommunityInvoiceLineView> sse_decode_list_community_invoice_line_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityInvoicePaymentView>
  sse_decode_list_community_invoice_payment_view(SseDeserializer deserializer);

  @protected
  List<CommunityInvoiceView> sse_decode_list_community_invoice_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityItemSalesView> sse_decode_list_community_item_sales_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityKitchenTicketLineView>
  sse_decode_list_community_kitchen_ticket_line_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityKitchenTicketView>
  sse_decode_list_community_kitchen_ticket_view(SseDeserializer deserializer);

  @protected
  List<CommunityModifierOptionView>
  sse_decode_list_community_modifier_option_view(SseDeserializer deserializer);

  @protected
  List<CommunityPaymentAllocation> sse_decode_list_community_payment_allocation(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityProductView> sse_decode_list_community_product_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunityStaffView> sse_decode_list_community_staff_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommunitySyncQueueItemView>
  sse_decode_list_community_sync_queue_item_view(SseDeserializer deserializer);

  @protected
  List<CommunityTaxRateView> sse_decode_list_community_tax_rate_view(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  CommunityOpenCashDrawer?
  sse_decode_opt_box_autoadd_community_open_cash_drawer(
    SseDeserializer deserializer,
  );

  @protected
  GotiginCatalogMenuImageSelection?
  sse_decode_opt_box_autoadd_gotigin_catalog_menu_image_selection(
    SseDeserializer deserializer,
  );

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  List<CommunityPaymentAllocation>?
  sse_decode_opt_list_community_payment_allocation(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_community_open_cash_drawer(
    CommunityOpenCashDrawer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gotigin_catalog_menu_image_selection(
    GotiginCatalogMenuImageSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_audit_event_view(
    CommunityAuditEventView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_audit_timeline(
    CommunityAuditTimeline self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_backup_result(
    CommunityBackupResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_cart_line(
    CommunityCartLine self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_cash_drawer_result(
    CommunityCashDrawerResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_category_view(
    CommunityCategoryView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_customer_view(
    CommunityCustomerView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_diagnostic_event_view(
    CommunityDiagnosticEventView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_diagnostics_pack(
    CommunityDiagnosticsPack self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_diagnostics_share_result(
    CommunityDiagnosticsShareResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_diagnostics_workspace(
    CommunityDiagnosticsWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_draft_order_result(
    CommunityDraftOrderResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_draft_order_view(
    CommunityDraftOrderView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_expense_view(
    CommunityExpenseView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_expenses_workspace(
    CommunityExpensesWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_financial_csv_export(
    CommunityFinancialCsvExport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_inventory_item_view(
    CommunityInventoryItemView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_inventory_workspace(
    CommunityInventoryWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_invoice_detail(
    CommunityInvoiceDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_invoice_line_view(
    CommunityInvoiceLineView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_invoice_payment_view(
    CommunityInvoicePaymentView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_invoice_view(
    CommunityInvoiceView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_item_sales_view(
    CommunityItemSalesView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_kitchen_ticket_line_view(
    CommunityKitchenTicketLineView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_kitchen_ticket_view(
    CommunityKitchenTicketView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_modifier_option_view(
    CommunityModifierOptionView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_open_cash_drawer(
    CommunityOpenCashDrawer self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_payment_allocation(
    CommunityPaymentAllocation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_product_view(
    CommunityProductView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_sale_pricing_preview(
    CommunitySalePricingPreview self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_sale_result(
    CommunitySaleResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_sales_summary(
    CommunitySalesSummary self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_staff_security(
    CommunityStaffSecurity self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_staff_view(
    CommunityStaffView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_sync_queue(
    CommunitySyncQueue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_sync_queue_item_view(
    CommunitySyncQueueItemView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_tax_rate_view(
    CommunityTaxRateView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_tax_rate_workspace(
    CommunityTaxRateWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_community_workspace(
    CommunityWorkspace self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gotigin_catalog_menu_image_selection(
    GotiginCatalogMenuImageSelection self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_community_audit_event_view(
    List<CommunityAuditEventView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_cart_line(
    List<CommunityCartLine> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_category_view(
    List<CommunityCategoryView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_customer_view(
    List<CommunityCustomerView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_diagnostic_event_view(
    List<CommunityDiagnosticEventView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_draft_order_view(
    List<CommunityDraftOrderView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_expense_view(
    List<CommunityExpenseView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_inventory_item_view(
    List<CommunityInventoryItemView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_invoice_line_view(
    List<CommunityInvoiceLineView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_invoice_payment_view(
    List<CommunityInvoicePaymentView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_invoice_view(
    List<CommunityInvoiceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_item_sales_view(
    List<CommunityItemSalesView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_kitchen_ticket_line_view(
    List<CommunityKitchenTicketLineView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_kitchen_ticket_view(
    List<CommunityKitchenTicketView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_modifier_option_view(
    List<CommunityModifierOptionView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_payment_allocation(
    List<CommunityPaymentAllocation> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_product_view(
    List<CommunityProductView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_staff_view(
    List<CommunityStaffView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_sync_queue_item_view(
    List<CommunitySyncQueueItemView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_community_tax_rate_view(
    List<CommunityTaxRateView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_community_open_cash_drawer(
    CommunityOpenCashDrawer? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_gotigin_catalog_menu_image_selection(
    GotiginCatalogMenuImageSelection? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_community_payment_allocation(
    List<CommunityPaymentAllocation>? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
