// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `chrono_like_utc_now`, `community_database_path`, `diagnostic_app_channel`, `diagnostic_component_label`, `diagnostic_outcome_label`, `diagnostic_platform`, `load_or_migrate_profile_registry`, `locked_workspace`, `normalize_gotigin_catalog_menu_image`, `normalize_restaurant_menu_image`, `open_community_database`, `parse_order_discount`, `profile_registry_path`, `record_diagnostic`, `save_profile_registry`, `selected_menu_item_image`, `unavailable_audit_timeline`, `unavailable_backup`, `unavailable_cash_drawer`, `unavailable_diagnostics_pack`, `unavailable_diagnostics`, `unavailable_draft`, `unavailable_expenses`, `unavailable_financial_csv_export`, `unavailable_inventory`, `unavailable_invoice_detail`, `unavailable_profile_registry`, `unavailable_sale_pricing_preview`, `unavailable_sale`, `unavailable_sales_summary`, `unavailable_staff_security`, `unavailable_sync_queue`, `unavailable_workspace`, `user_safe_bootstrap_status`, `workspace_with_error`, `workspace_with_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProfileRegistryEntry`, `ProfileRegistryFile`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`

String localCoreStatus() =>
    RustLib.instance.api.crateApiSimpleLocalCoreStatus();

/// Prepares the encrypted local database without exposing its key to Flutter.
/// This is deliberately asynchronous at the bridge boundary: OS credential
/// stores and first-open migrations may block briefly and must not freeze the
/// cashier-facing Dart UI.
Future<String> bootstrapLocalStorage({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleBootstrapLocalStorage(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Loads the Rust-owned local staff state. The lock UI may select a staff
/// record but never supplies a role or actor identity for a later mutation.
Future<CommunityStaffSecurity> loadCommunityStaffSecurity({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityStaffSecurity(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Sets the owner PIN once with a recovery passphrase, then creates the first
/// short-lived owner session so onboarding can continue without a second
/// plaintext PIN prompt.
Future<CommunityStaffSecurity> configureCommunityOwnerPin({
  required String applicationSupportDirectory,
  required String pin,
  required String recoveryPassphrase,
}) => RustLib.instance.api.crateApiSimpleConfigureCommunityOwnerPin(
  applicationSupportDirectory: applicationSupportDirectory,
  pin: pin,
  recoveryPassphrase: recoveryPassphrase,
);

Future<CommunityStaffSecurity> recoverCommunityOwnerPin({
  required String applicationSupportDirectory,
  required String recoveryPassphrase,
  required String newOwnerPin,
}) => RustLib.instance.api.crateApiSimpleRecoverCommunityOwnerPin(
  applicationSupportDirectory: applicationSupportDirectory,
  recoveryPassphrase: recoveryPassphrase,
  newOwnerPin: newOwnerPin,
);

Future<CommunityStaffSecurity> unlockCommunityStaff({
  required String applicationSupportDirectory,
  required String staffId,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleUnlockCommunityStaff(
  applicationSupportDirectory: applicationSupportDirectory,
  staffId: staffId,
  pin: pin,
);

Future<CommunityStaffSecurity> lockCommunityStaff({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLockCommunityStaff(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Owner-only Community staff enrollment. A role is parsed in Rust and the
/// active local session—not Flutter—supplies the acting owner identity.
Future<CommunityStaffSecurity> createCommunityStaff({
  required String applicationSupportDirectory,
  required String displayName,
  required String role,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityStaff(
  applicationSupportDirectory: applicationSupportDirectory,
  displayName: displayName,
  role: role,
  pin: pin,
);

/// Owner-only, append-only change of a non-owner staff member's effective
/// role. Flutter supplies neither authority nor a mutable staff record.
Future<CommunityStaffSecurity> changeCommunityStaffRole({
  required String applicationSupportDirectory,
  required String staffId,
  required String role,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleChangeCommunityStaffRole(
  applicationSupportDirectory: applicationSupportDirectory,
  staffId: staffId,
  role: role,
  reason: reason,
);

Future<CommunityStaffSecurity> rotateCommunityStaffPin({
  required String applicationSupportDirectory,
  required String staffId,
  required String pin,
}) => RustLib.instance.api.crateApiSimpleRotateCommunityStaffPin(
  applicationSupportDirectory: applicationSupportDirectory,
  staffId: staffId,
  pin: pin,
);

Future<CommunityStaffSecurity> revokeCommunityStaff({
  required String applicationSupportDirectory,
  required String staffId,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleRevokeCommunityStaff(
  applicationSupportDirectory: applicationSupportDirectory,
  staffId: staffId,
  reason: reason,
);

/// Explicit installer recovery when a secure device key exists without its
/// encrypted database. Never runs automatically during ordinary bootstrap.
Future<CommunityWorkspace> resetCommunityStorageForFreshSetup({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleResetCommunityStorageForFreshSetup(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityWorkspace> loadCommunityWorkspace({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityWorkspace(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunitySalesSummary> loadCommunitySalesSummary({
  required String applicationSupportDirectory,
  String? accountingDateUtc,
}) => RustLib.instance.api.crateApiSimpleLoadCommunitySalesSummary(
  applicationSupportDirectory: applicationSupportDirectory,
  accountingDateUtc: accountingDateUtc,
);

/// Prepares a bounded RFC-4180 CSV only after encrypted storage has verified
/// the active Owner session, database integrity, schema, foreign keys, audit
/// chains, and financial-fact consistency. Flutter must display a native save
/// dialog before these in-memory bytes leave the device.
Future<CommunityFinancialCsvExport> prepareCommunityFinancialCsv({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimplePrepareCommunityFinancialCsv(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Loads the recent owner-visible audit timeline only after full local
/// integrity verification. Flutter receives a safe projection rather than raw
/// payloads, hash-chain material, credentials, or staff/device identifiers.
Future<CommunityAuditTimeline> loadCommunityAuditTimeline({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityAuditTimeline(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Loads the local Professional sync outbox as a privacy-safe owner view.
/// This does not contact the cloud; it only surfaces how many immutable local
/// operations are still waiting for a future acknowledgement.
Future<CommunitySyncQueue> loadCommunitySyncQueue({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunitySyncQueue(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Reprints one historical receipt from immutable order, invoice, and payment
/// snapshots. Counter-capable staff can read only the requested receipt in
/// their active branch; the Flutter caller never queries SQLite directly.
Future<CommunityInvoiceDetail> loadCommunityInvoiceDetail({
  required String applicationSupportDirectory,
  required String invoiceId,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityInvoiceDetail(
  applicationSupportDirectory: applicationSupportDirectory,
  invoiceId: invoiceId,
);

/// Loads branch inventory from the encrypted, append-only movement ledger.
/// An item is tracked only after its first explicit stock movement.
Future<CommunityInventoryWorkspace> loadCommunityInventory({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityInventory(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Records one validated Community inventory command. Flutter supplies only
/// identity, movement, quantity, and rationale; Rust owns authority and data
/// validation before touching encrypted storage.
Future<CommunityInventoryWorkspace> recordCommunityInventoryMovement({
  required String applicationSupportDirectory,
  required String productId,
  required String movementType,
  required PlatformInt64 quantity,
  String? reason,
}) => RustLib.instance.api.crateApiSimpleRecordCommunityInventoryMovement(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  movementType: movementType,
  quantity: quantity,
  reason: reason,
);

/// Appends an owner/manager-selected replenishment threshold for a tracked
/// product. A threshold affects only the low-stock indicator, never quantity.
Future<CommunityInventoryWorkspace> setCommunityInventoryLowStockThreshold({
  required String applicationSupportDirectory,
  required String productId,
  required PlatformInt64 thresholdQuantity,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleSetCommunityInventoryLowStockThreshold(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  thresholdQuantity: thresholdQuantity,
  reason: reason,
);

/// Retains an explicit clear event for the current low-stock policy. This
/// removes the alert without mutating or deleting any previous threshold.
Future<CommunityInventoryWorkspace> clearCommunityInventoryLowStockThreshold({
  required String applicationSupportDirectory,
  required String productId,
  required String reason,
}) =>
    RustLib.instance.api.crateApiSimpleClearCommunityInventoryLowStockThreshold(
      applicationSupportDirectory: applicationSupportDirectory,
      productId: productId,
      reason: reason,
    );

Future<CommunityExpensesWorkspace> loadCommunityExpenses({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityExpenses(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityExpensesWorkspace> recordCommunityExpense({
  required String applicationSupportDirectory,
  required String category,
  required String description,
  required PlatformInt64 amountMinor,
  required String paymentMethod,
}) => RustLib.instance.api.crateApiSimpleRecordCommunityExpense(
  applicationSupportDirectory: applicationSupportDirectory,
  category: category,
  description: description,
  amountMinor: amountMinor,
  paymentMethod: paymentMethod,
);

Future<CommunityCashDrawerResult> openCommunityCashDrawer({
  required String applicationSupportDirectory,
  required PlatformInt64 openingCashMinor,
}) => RustLib.instance.api.crateApiSimpleOpenCommunityCashDrawer(
  applicationSupportDirectory: applicationSupportDirectory,
  openingCashMinor: openingCashMinor,
);

Future<CommunityOpenCashDrawer?> loadCommunityOpenCashDrawer({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityOpenCashDrawer(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityCashDrawerResult> closeCommunityCashDrawer({
  required String applicationSupportDirectory,
  required String sessionId,
  required PlatformInt64 countedCashMinor,
}) => RustLib.instance.api.crateApiSimpleCloseCommunityCashDrawer(
  applicationSupportDirectory: applicationSupportDirectory,
  sessionId: sessionId,
  countedCashMinor: countedCashMinor,
);

/// Records an owner/manager-authorized refund as a new immutable fact. The
/// amount may be a full remaining balance or a controlled partial refund; Rust
/// revalidates the remaining invoice total and original tender allocations.
Future<CommunitySalesSummary> refundCommunityInvoice({
  required String applicationSupportDirectory,
  required String invoiceId,
  required PlatformInt64 amountMinor,
  required String reason,
  required String approverStaffId,
  required String approverPin,
  String? accountingDateUtc,
}) => RustLib.instance.api.crateApiSimpleRefundCommunityInvoice(
  applicationSupportDirectory: applicationSupportDirectory,
  invoiceId: invoiceId,
  amountMinor: amountMinor,
  reason: reason,
  approverStaffId: approverStaffId,
  approverPin: approverPin,
  accountingDateUtc: accountingDateUtc,
);

Future<CommunityPortableBackupResult> createCommunityPortableBackup({
  required String applicationSupportDirectory,
  required String recoveryPassphrase,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityPortableBackup(
  applicationSupportDirectory: applicationSupportDirectory,
  recoveryPassphrase: recoveryPassphrase,
);

Future<CommunityRestaurantProfileRegistry> restoreCommunityPortableBackup({
  required String applicationSupportDirectory,
  required String backupFilePath,
  required String envelopeFilePath,
  required String recoveryPassphrase,
  required String profileLabel,
}) => RustLib.instance.api.crateApiSimpleRestoreCommunityPortableBackup(
  applicationSupportDirectory: applicationSupportDirectory,
  backupFilePath: backupFilePath,
  envelopeFilePath: envelopeFilePath,
  recoveryPassphrase: recoveryPassphrase,
  profileLabel: profileLabel,
);

Future<CommunityRestaurantProfileRegistry> listCommunityRestaurantProfiles({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleListCommunityRestaurantProfiles(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityRestaurantProfileRegistry> setCommunityEditionAndDeviceRole({
  required String applicationSupportDirectory,
  required String edition,
  required String deviceRole,
}) => RustLib.instance.api.crateApiSimpleSetCommunityEditionAndDeviceRole(
  applicationSupportDirectory: applicationSupportDirectory,
  edition: edition,
  deviceRole: deviceRole,
);

Future<CommunityRestaurantProfileRegistry> startNewCommunityRestaurantProfile({
  required String applicationSupportDirectory,
  required String label,
}) => RustLib.instance.api.crateApiSimpleStartNewCommunityRestaurantProfile(
  applicationSupportDirectory: applicationSupportDirectory,
  label: label,
);

Future<CommunityRestaurantProfileRegistry> activateCommunityRestaurantProfile({
  required String applicationSupportDirectory,
  required String profileId,
}) => RustLib.instance.api.crateApiSimpleActivateCommunityRestaurantProfile(
  applicationSupportDirectory: applicationSupportDirectory,
  profileId: profileId,
);

Future<CommunityBackupResult> createCommunityLocalBackup({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityLocalBackup(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityBackupResult> verifyCommunityLocalBackup({
  required String applicationSupportDirectory,
  required String backupFileName,
}) => RustLib.instance.api.crateApiSimpleVerifyCommunityLocalBackup(
  applicationSupportDirectory: applicationSupportDirectory,
  backupFileName: backupFileName,
);

Future<CommunityBackupResult> restoreCommunityLocalBackup({
  required String applicationSupportDirectory,
  required String backupFileName,
}) => RustLib.instance.api.crateApiSimpleRestoreCommunityLocalBackup(
  applicationSupportDirectory: applicationSupportDirectory,
  backupFileName: backupFileName,
);

Future<CommunitySalesSummary> voidCommunityInvoice({
  required String applicationSupportDirectory,
  required String invoiceId,
  required String reason,
  required String approverStaffId,
  required String approverPin,
  String? accountingDateUtc,
}) => RustLib.instance.api.crateApiSimpleVoidCommunityInvoice(
  applicationSupportDirectory: applicationSupportDirectory,
  invoiceId: invoiceId,
  reason: reason,
  approverStaffId: approverStaffId,
  approverPin: approverPin,
  accountingDateUtc: accountingDateUtc,
);

/// Closes one UTC accounting day with an immutable snapshot. Reopen is not
/// offered; founder policy is required before any dual-approval reopen path.
Future<CommunitySalesSummary> closeCommunityAccountingDay({
  required String applicationSupportDirectory,
  required String accountingDateUtc,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleCloseCommunityAccountingDay(
  applicationSupportDirectory: applicationSupportDirectory,
  accountingDateUtc: accountingDateUtc,
  reason: reason,
);

/// Records an allow-listed UI breadcrumb. Unknown codes are rejected in Rust
/// and never written.
Future<bool> recordCommunityDiagnosticBreadcrumb({
  required String applicationSupportDirectory,
  required String eventCode,
  String? detailCode,
}) => RustLib.instance.api.crateApiSimpleRecordCommunityDiagnosticBreadcrumb(
  applicationSupportDirectory: applicationSupportDirectory,
  eventCode: eventCode,
  detailCode: detailCode,
);

/// Owner-only recent diagnostics projection. Payloads stay allow-listed codes.
Future<CommunityDiagnosticsWorkspace> loadCommunityDiagnostics({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleLoadCommunityDiagnostics(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Owner-only redacted diagnostics pack for native save or voluntary share.
Future<CommunityDiagnosticsPack> exportCommunityDiagnosticsPack({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleExportCommunityDiagnosticsPack(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Prepares an Owner-consented share pack. Upload is performed by Flutter only
/// after consent; Rust records the attempt outcome category supplied by Flutter.
Future<CommunityDiagnosticsShareResult> prepareCommunityDiagnosticsShare({
  required String applicationSupportDirectory,
  required String purpose,
}) => RustLib.instance.api.crateApiSimplePrepareCommunityDiagnosticsShare(
  applicationSupportDirectory: applicationSupportDirectory,
  purpose: purpose,
);

/// Records whether a voluntary Flutter-side upload succeeded. Never uploads itself.
Future<bool> recordCommunityDiagnosticsShareOutcome({
  required String applicationSupportDirectory,
  required bool uploaded,
}) => RustLib.instance.api.crateApiSimpleRecordCommunityDiagnosticsShareOutcome(
  applicationSupportDirectory: applicationSupportDirectory,
  uploaded: uploaded,
);

/// Owner-only clear of local diagnostic files.
Future<bool> clearCommunityDiagnostics({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleClearCommunityDiagnostics(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityWorkspace> completeCommunitySetup({
  required String applicationSupportDirectory,
  required String organizationName,
  required String branchName,
  required String currencyCode,
  required String timeZone,
}) => RustLib.instance.api.crateApiSimpleCompleteCommunitySetup(
  applicationSupportDirectory: applicationSupportDirectory,
  organizationName: organizationName,
  branchName: branchName,
  currencyCode: currencyCode,
  timeZone: timeZone,
);

Future<CommunityWorkspace> createCommunityCategory({
  required String applicationSupportDirectory,
  required String displayName,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityCategory(
  applicationSupportDirectory: applicationSupportDirectory,
  displayName: displayName,
);

/// Imports an editable Indian restaurant starter menu. Every item is imported
/// available at a one-unit placeholder price so the owner can try POS
/// immediately, then replace prices when ready.
Future<CommunityWorkspace> importCommonStarterMenu({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleImportCommonStarterMenu(
  applicationSupportDirectory: applicationSupportDirectory,
);

/// Enrolls a customer as an active local profile. The active staff session
/// supplies the actor identity and role; the client cannot impersonate one.
Future<CommunityWorkspace> createCommunityCustomer({
  required String applicationSupportDirectory,
  required String displayName,
  String? phoneNumber,
  String? emailAddress,
  required bool marketingConsent,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityCustomer(
  applicationSupportDirectory: applicationSupportDirectory,
  displayName: displayName,
  phoneNumber: phoneNumber,
  emailAddress: emailAddress,
  marketingConsent: marketingConsent,
);

/// Appends a corrected profile revision. The correction rationale is retained
/// in the local audit trail while prior profile facts remain immutable.
Future<CommunityWorkspace> reviseCommunityCustomer({
  required String applicationSupportDirectory,
  required String customerId,
  required String displayName,
  String? phoneNumber,
  String? emailAddress,
  required bool marketingConsent,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleReviseCommunityCustomer(
  applicationSupportDirectory: applicationSupportDirectory,
  customerId: customerId,
  displayName: displayName,
  phoneNumber: phoneNumber,
  emailAddress: emailAddress,
  marketingConsent: marketingConsent,
  reason: reason,
);

/// Appends an anonymized current profile. Existing invoices remain intact but
/// the record cannot be selected for a new sale.
Future<CommunityWorkspace> anonymizeCommunityCustomer({
  required String applicationSupportDirectory,
  required String customerId,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleAnonymizeCommunityCustomer(
  applicationSupportDirectory: applicationSupportDirectory,
  customerId: customerId,
  reason: reason,
);

Future<CommunityWorkspace> createCommunityProduct({
  required String applicationSupportDirectory,
  required String displayName,
  required String categoryId,
  required PlatformInt64 unitPriceMinor,
  String? builtInImageKey,
  Uint8List? restaurantImageBytes,
  GotiginCatalogMenuImageSelection? gotiginCatalogImage,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityProduct(
  applicationSupportDirectory: applicationSupportDirectory,
  displayName: displayName,
  categoryId: categoryId,
  unitPriceMinor: unitPriceMinor,
  builtInImageKey: builtInImageKey,
  restaurantImageBytes: restaurantImageBytes,
  gotiginCatalogImage: gotiginCatalogImage,
);

/// Adds a product-bound, append-only modifier option. Flutter supplies only a
/// display label and minor-unit delta; Rust resolves the branch currency and
/// records the immutable catalogue/audit/outbox facts atomically.
Future<CommunityWorkspace> createCommunityProductModifierOption({
  required String applicationSupportDirectory,
  required String productId,
  required String displayName,
  required PlatformInt64 priceDeltaMinor,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityProductModifierOption(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  displayName: displayName,
  priceDeltaMinor: priceDeltaMinor,
);

/// Archives one immutable option without deleting it. Earlier order, kitchen,
/// invoice, and audit snapshots continue to render the original selection.
Future<CommunityWorkspace> archiveCommunityProductModifierOption({
  required String applicationSupportDirectory,
  required String modifierOptionId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleArchiveCommunityProductModifierOption(
  applicationSupportDirectory: applicationSupportDirectory,
  modifierOptionId: modifierOptionId,
  expectedRevision: expectedRevision,
  reason: reason,
);

Future<CommunityTaxRateWorkspace> listCommunityTaxRates({
  required String applicationSupportDirectory,
}) => RustLib.instance.api.crateApiSimpleListCommunityTaxRates(
  applicationSupportDirectory: applicationSupportDirectory,
);

Future<CommunityTaxRateWorkspace> createCommunityTaxRate({
  required String applicationSupportDirectory,
  required String displayName,
  required PlatformInt64 basisPoints,
}) => RustLib.instance.api.crateApiSimpleCreateCommunityTaxRate(
  applicationSupportDirectory: applicationSupportDirectory,
  displayName: displayName,
  basisPoints: basisPoints,
);

Future<CommunityTaxRateWorkspace> archiveCommunityTaxRate({
  required String applicationSupportDirectory,
  required String taxRateId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleArchiveCommunityTaxRate(
  applicationSupportDirectory: applicationSupportDirectory,
  taxRateId: taxRateId,
  expectedRevision: expectedRevision,
  reason: reason,
);

Future<CommunityWorkspace> setCommunityProductTaxTreatment({
  required String applicationSupportDirectory,
  required String productId,
  required String taxTreatment,
  required PlatformInt64 expectedRevision,
}) => RustLib.instance.api.crateApiSimpleSetCommunityProductTaxTreatment(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  taxTreatment: taxTreatment,
  expectedRevision: expectedRevision,
);

/// Prepares a selected image before it is accepted by the Flutter form. This
/// keeps the expensive decoding and re-encoding in Rust, removes metadata,
/// and enforces the 3 MiB post-compression acceptance ceiling. An empty return
/// is intentionally a safe, detail-free rejection for untrusted input.
Future<Uint8List> prepareCommunityMenuImage({required List<int> imageBytes}) =>
    RustLib.instance.api.crateApiSimplePrepareCommunityMenuImage(
      imageBytes: imageBytes,
    );

/// Applies a reasoned selling-price change. The encrypted storage core uses a
/// revision check and records before/after values, while past invoices retain
/// their already-snapshotted line price.
Future<CommunityWorkspace> updateCommunityProductPrice({
  required String applicationSupportDirectory,
  required String productId,
  required PlatformInt64 expectedRevision,
  required PlatformInt64 unitPriceMinor,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleUpdateCommunityProductPrice(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  expectedRevision: expectedRevision,
  unitPriceMinor: unitPriceMinor,
  reason: reason,
);

/// Temporarily removes an active menu item from checkout, or resumes it,
/// without mutating its financial history. The storage core requires a
/// management role, a current revision, and a human-readable reason.
Future<CommunityWorkspace> setCommunityProductAvailability({
  required String applicationSupportDirectory,
  required String productId,
  required PlatformInt64 expectedRevision,
  required bool isAvailable,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleSetCommunityProductAvailability(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  expectedRevision: expectedRevision,
  isAvailable: isAvailable,
  reason: reason,
);

/// Removes an item from the active menu without deleting it. The product,
/// selected image versions, sales references, and audit record stay intact for
/// reconciliation and future sync.
Future<CommunityWorkspace> archiveCommunityProduct({
  required String applicationSupportDirectory,
  required String productId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleArchiveCommunityProduct(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Removes an empty category, or a category whose items have never been sold,
/// from the active catalogue. Retained transactions prevent removal.
Future<CommunityWorkspace> archiveCommunityCategory({
  required String applicationSupportDirectory,
  required String categoryId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleArchiveCommunityCategory(
  applicationSupportDirectory: applicationSupportDirectory,
  categoryId: categoryId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Replaces a category image with category-specific app artwork, a verified
/// Gotigin catalogue image, or a restaurant-owned upload.
Future<CommunityWorkspace> replaceCommunityCategoryImage({
  required String applicationSupportDirectory,
  required String categoryId,
  Uint8List? restaurantImageBytes,
  String? builtInImageKey,
  GotiginCatalogMenuImageSelection? gotiginCatalogImage,
}) => RustLib.instance.api.crateApiSimpleReplaceCommunityCategoryImage(
  applicationSupportDirectory: applicationSupportDirectory,
  categoryId: categoryId,
  restaurantImageBytes: restaurantImageBytes,
  builtInImageKey: builtInImageKey,
  gotiginCatalogImage: gotiginCatalogImage,
);

/// Removes the current category visual without deleting the category or its
/// retained image/licence history.
Future<CommunityWorkspace> clearCommunityCategoryImage({
  required String applicationSupportDirectory,
  required String categoryId,
}) => RustLib.instance.api.crateApiSimpleClearCommunityCategoryImage(
  applicationSupportDirectory: applicationSupportDirectory,
  categoryId: categoryId,
);

/// Replaces the active menu image for a product by appending a new immutable
/// image version. Past sales retain their snapshotted catalogue facts.
Future<CommunityWorkspace> replaceCommunityProductImage({
  required String applicationSupportDirectory,
  required String productId,
  Uint8List? restaurantImageBytes,
  String? builtInImageKey,
}) => RustLib.instance.api.crateApiSimpleReplaceCommunityProductImage(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  restaurantImageBytes: restaurantImageBytes,
  builtInImageKey: builtInImageKey,
);

/// Permanently deletes an unused menu item only when the storage policy proves
/// that it has no retained financial, image, or synchronization history.
Future<CommunityWorkspace> deleteUnusedCommunityProduct({
  required String applicationSupportDirectory,
  required String productId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleDeleteUnusedCommunityProduct(
  applicationSupportDirectory: applicationSupportDirectory,
  productId: productId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Saves an open order as a versioned local draft. The draft contains trusted
/// catalog snapshots and no payment or invoice facts.
Future<CommunityDraftOrderResult> saveCommunityDraftOrder({
  required String applicationSupportDirectory,
  String? draftOrderId,
  PlatformInt64? expectedRevision,
  required List<CommunityCartLine> cartLines,
  required String fulfillment,
  String? tableName,
  String? kitchenNote,
}) => RustLib.instance.api.crateApiSimpleSaveCommunityDraftOrder(
  applicationSupportDirectory: applicationSupportDirectory,
  draftOrderId: draftOrderId,
  expectedRevision: expectedRevision,
  cartLines: cartLines,
  fulfillment: fulfillment,
  tableName: tableName,
  kitchenNote: kitchenNote,
);

Future<CommunityWorkspace> cancelCommunityOpenDraftOrder({
  required String applicationSupportDirectory,
  required String draftOrderId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleCancelCommunityOpenDraftOrder(
  applicationSupportDirectory: applicationSupportDirectory,
  draftOrderId: draftOrderId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Sends an immutable stop-work notice to kitchen and closes the selected
/// sent draft. Only an active owner or manager session can perform this
/// action; kitchen receives the signal but not the counter rationale.
Future<CommunityWorkspace> cancelCommunitySentDraftOrder({
  required String applicationSupportDirectory,
  required String draftOrderId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleCancelCommunitySentDraftOrder(
  applicationSupportDirectory: applicationSupportDirectory,
  draftOrderId: draftOrderId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Preserves the original kitchen ticket, sends its cancellation notice, and
/// creates a separate editable draft revision for a counter correction.
Future<CommunityWorkspace> reopenCommunitySentDraftOrder({
  required String applicationSupportDirectory,
  required String draftOrderId,
  required PlatformInt64 expectedRevision,
  required String reason,
}) => RustLib.instance.api.crateApiSimpleReopenCommunitySentDraftOrder(
  applicationSupportDirectory: applicationSupportDirectory,
  draftOrderId: draftOrderId,
  expectedRevision: expectedRevision,
  reason: reason,
);

/// Records that an authorized kitchen session has seen a counter cancellation
/// notice. This removes it from the active kitchen queue while retaining both
/// the request and acknowledgement as immutable audit facts.
Future<CommunityWorkspace> acknowledgeCommunityKitchenTicketCancellation({
  required String applicationSupportDirectory,
  required String ticketId,
}) => RustLib.instance.api
    .crateApiSimpleAcknowledgeCommunityKitchenTicketCancellation(
      applicationSupportDirectory: applicationSupportDirectory,
      ticketId: ticketId,
    );

Future<CommunityWorkspace> sendCommunityDraftToKitchen({
  required String applicationSupportDirectory,
  required String draftOrderId,
  required PlatformInt64 expectedRevision,
}) => RustLib.instance.api.crateApiSimpleSendCommunityDraftToKitchen(
  applicationSupportDirectory: applicationSupportDirectory,
  draftOrderId: draftOrderId,
  expectedRevision: expectedRevision,
);

Future<CommunityWorkspace> advanceCommunityKitchenTicket({
  required String applicationSupportDirectory,
  required String ticketId,
  required PlatformInt64 expectedRevision,
  required String nextState,
}) => RustLib.instance.api.crateApiSimpleAdvanceCommunityKitchenTicket(
  applicationSupportDirectory: applicationSupportDirectory,
  ticketId: ticketId,
  expectedRevision: expectedRevision,
  nextState: nextState,
);

/// Calculates the trusted payable total for the current cart without recording
/// a sale. Split tender and checkout previews must use this path.
Future<CommunitySalePricingPreview> previewCommunitySalePricing({
  required String applicationSupportDirectory,
  required List<CommunityCartLine> cartLines,
  PlatformInt64? discountFixedMinor,
  PlatformInt64? discountPercentageBasisPoints,
  PlatformInt64? discountPercentageCapMinor,
  String? discountReason,
}) => RustLib.instance.api.crateApiSimplePreviewCommunitySalePricing(
  applicationSupportDirectory: applicationSupportDirectory,
  cartLines: cartLines,
  discountFixedMinor: discountFixedMinor,
  discountPercentageBasisPoints: discountPercentageBasisPoints,
  discountPercentageCapMinor: discountPercentageCapMinor,
  discountReason: discountReason,
);

/// Records a complete immediate counter sale. This Stage 1 vertical slice does
/// not create persistent drafts: a successful response means the order,
/// invoice, payment, audit envelopes, and future-sync outbox entries all
/// committed together in the encrypted local database.
Future<CommunitySaleResult> completeCommunitySale({
  required String applicationSupportDirectory,
  required List<CommunityCartLine> cartLines,
  required String fulfillment,
  required String paymentMethod,
  List<CommunityPaymentAllocation>? paymentAllocations,
  String? customerId,
  String? draftOrderId,
  PlatformInt64? expectedDraftRevision,
  PlatformInt64? discountFixedMinor,
  PlatformInt64? discountPercentageBasisPoints,
  PlatformInt64? discountPercentageCapMinor,
  String? discountReason,
}) => RustLib.instance.api.crateApiSimpleCompleteCommunitySale(
  applicationSupportDirectory: applicationSupportDirectory,
  cartLines: cartLines,
  fulfillment: fulfillment,
  paymentMethod: paymentMethod,
  paymentAllocations: paymentAllocations,
  customerId: customerId,
  draftOrderId: draftOrderId,
  expectedDraftRevision: expectedDraftRevision,
  discountFixedMinor: discountFixedMinor,
  discountPercentageBasisPoints: discountPercentageBasisPoints,
  discountPercentageCapMinor: discountPercentageCapMinor,
  discountReason: discountReason,
);

class CommunityAuditEventView {
  final PlatformInt64 sequence;
  final String eventType;
  final String occurredAtUtc;

  const CommunityAuditEventView({
    required this.sequence,
    required this.eventType,
    required this.occurredAtUtc,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^ eventType.hashCode ^ occurredAtUtc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityAuditEventView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          eventType == other.eventType &&
          occurredAtUtc == other.occurredAtUtc;
}

/// Owner-only local audit view. It intentionally excludes audit payloads,
/// identifiers, hashes, and device metadata.
class CommunityAuditTimeline {
  final String storageStatus;
  final bool available;
  final List<CommunityAuditEventView> events;

  const CommunityAuditTimeline({
    required this.storageStatus,
    required this.available,
    required this.events,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^ available.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityAuditTimeline &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          events == other.events;
}

class CommunityBackupResult {
  final String storageStatus;
  final bool created;
  final String? backupFileName;
  final String? sha256;

  const CommunityBackupResult({
    required this.storageStatus,
    required this.created,
    this.backupFileName,
    this.sha256,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      created.hashCode ^
      backupFileName.hashCode ^
      sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityBackupResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          created == other.created &&
          backupFileName == other.backupFileName &&
          sha256 == other.sha256;
}

/// An untrusted selection from the Flutter cart. It intentionally contains no
/// price, tax, invoice, or timestamp fields: Rust derives those facts from the
/// encrypted catalog and its transaction clock.
class CommunityCartLine {
  final String productId;
  final PlatformInt64 quantity;
  final List<String> modifierOptionIds;

  const CommunityCartLine({
    required this.productId,
    required this.quantity,
    required this.modifierOptionIds,
  });

  @override
  int get hashCode =>
      productId.hashCode ^ quantity.hashCode ^ modifierOptionIds.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityCartLine &&
          runtimeType == other.runtimeType &&
          productId == other.productId &&
          quantity == other.quantity &&
          modifierOptionIds == other.modifierOptionIds;
}

class CommunityCashDrawerResult {
  final String storageStatus;
  final bool completed;
  final String? sessionId;
  final PlatformInt64 expectedCashMinor;
  final PlatformInt64 countedCashMinor;
  final PlatformInt64 varianceMinor;

  const CommunityCashDrawerResult({
    required this.storageStatus,
    required this.completed,
    this.sessionId,
    required this.expectedCashMinor,
    required this.countedCashMinor,
    required this.varianceMinor,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      completed.hashCode ^
      sessionId.hashCode ^
      expectedCashMinor.hashCode ^
      countedCashMinor.hashCode ^
      varianceMinor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityCashDrawerResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          completed == other.completed &&
          sessionId == other.sessionId &&
          expectedCashMinor == other.expectedCashMinor &&
          countedCashMinor == other.countedCashMinor &&
          varianceMinor == other.varianceMinor;
}

class CommunityCategoryView {
  final String categoryId;
  final String displayName;
  final PlatformInt64 revision;
  final String? imageAssetKey;
  final Uint8List? imageBytes;

  const CommunityCategoryView({
    required this.categoryId,
    required this.displayName,
    required this.revision,
    this.imageAssetKey,
    this.imageBytes,
  });

  @override
  int get hashCode =>
      categoryId.hashCode ^
      displayName.hashCode ^
      revision.hashCode ^
      imageAssetKey.hashCode ^
      imageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityCategoryView &&
          runtimeType == other.runtimeType &&
          categoryId == other.categoryId &&
          displayName == other.displayName &&
          revision == other.revision &&
          imageAssetKey == other.imageAssetKey &&
          imageBytes == other.imageBytes;
}

/// Current, counter-safe customer projection. Earlier profile revisions and
/// anonymized identities never cross FFI, which keeps historical PII outside
/// the presentation layer by default.
class CommunityCustomerView {
  final String customerId;
  final String displayName;
  final String? phoneNumber;
  final String? emailAddress;
  final bool marketingConsent;
  final PlatformInt64 revision;

  const CommunityCustomerView({
    required this.customerId,
    required this.displayName,
    this.phoneNumber,
    this.emailAddress,
    required this.marketingConsent,
    required this.revision,
  });

  @override
  int get hashCode =>
      customerId.hashCode ^
      displayName.hashCode ^
      phoneNumber.hashCode ^
      emailAddress.hashCode ^
      marketingConsent.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityCustomerView &&
          runtimeType == other.runtimeType &&
          customerId == other.customerId &&
          displayName == other.displayName &&
          phoneNumber == other.phoneNumber &&
          emailAddress == other.emailAddress &&
          marketingConsent == other.marketingConsent &&
          revision == other.revision;
}

/// Owner-facing, privacy-allowlisted diagnostic event for local troubleshooting.
class CommunityDiagnosticEventView {
  final String occurredAtUtc;
  final String eventCode;
  final String component;
  final String outcome;
  final PlatformInt64? durationMs;
  final String? detailCode;

  const CommunityDiagnosticEventView({
    required this.occurredAtUtc,
    required this.eventCode,
    required this.component,
    required this.outcome,
    this.durationMs,
    this.detailCode,
  });

  @override
  int get hashCode =>
      occurredAtUtc.hashCode ^
      eventCode.hashCode ^
      component.hashCode ^
      outcome.hashCode ^
      durationMs.hashCode ^
      detailCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDiagnosticEventView &&
          runtimeType == other.runtimeType &&
          occurredAtUtc == other.occurredAtUtc &&
          eventCode == other.eventCode &&
          component == other.component &&
          outcome == other.outcome &&
          durationMs == other.durationMs &&
          detailCode == other.detailCode;
}

class CommunityDiagnosticsPack {
  final String storageStatus;
  final bool available;
  final Uint8List jsonBytes;
  final String? sha256;
  final PlatformInt64 eventCount;
  final PlatformInt64 byteLength;

  const CommunityDiagnosticsPack({
    required this.storageStatus,
    required this.available,
    required this.jsonBytes,
    this.sha256,
    required this.eventCount,
    required this.byteLength,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      jsonBytes.hashCode ^
      sha256.hashCode ^
      eventCount.hashCode ^
      byteLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDiagnosticsPack &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          jsonBytes == other.jsonBytes &&
          sha256 == other.sha256 &&
          eventCount == other.eventCount &&
          byteLength == other.byteLength;
}

class CommunityDiagnosticsShareResult {
  final String storageStatus;
  final bool prepared;
  final bool uploaded;
  final String? sha256;
  final PlatformInt64 eventCount;
  final Uint8List jsonBytes;

  const CommunityDiagnosticsShareResult({
    required this.storageStatus,
    required this.prepared,
    required this.uploaded,
    this.sha256,
    required this.eventCount,
    required this.jsonBytes,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      prepared.hashCode ^
      uploaded.hashCode ^
      sha256.hashCode ^
      eventCount.hashCode ^
      jsonBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDiagnosticsShareResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          prepared == other.prepared &&
          uploaded == other.uploaded &&
          sha256 == other.sha256 &&
          eventCount == other.eventCount &&
          jsonBytes == other.jsonBytes;
}

class CommunityDiagnosticsWorkspace {
  final String storageStatus;
  final bool available;
  final List<CommunityDiagnosticEventView> events;

  const CommunityDiagnosticsWorkspace({
    required this.storageStatus,
    required this.available,
    required this.events,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^ available.hashCode ^ events.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDiagnosticsWorkspace &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          events == other.events;
}

class CommunityDraftOrderResult {
  final String storageStatus;
  final bool saved;
  final String? draftOrderId;
  final PlatformInt64 revision;

  const CommunityDraftOrderResult({
    required this.storageStatus,
    required this.saved,
    this.draftOrderId,
    required this.revision,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      saved.hashCode ^
      draftOrderId.hashCode ^
      revision.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDraftOrderResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          saved == other.saved &&
          draftOrderId == other.draftOrderId &&
          revision == other.revision;
}

class CommunityDraftOrderView {
  final String draftOrderId;
  final String fulfillment;
  final String draftState;
  final String? tableName;

  /// An optional operational instruction. It is bounded and normalized in
  /// Rust storage and becomes immutable once sent to Kitchen Display.
  final String? kitchenNote;
  final PlatformInt64 revision;
  final PlatformInt64 subtotalMinor;
  final String currencyCode;
  final PlatformInt64 lineCount;
  final List<CommunityCartLine> lines;

  const CommunityDraftOrderView({
    required this.draftOrderId,
    required this.fulfillment,
    required this.draftState,
    this.tableName,
    this.kitchenNote,
    required this.revision,
    required this.subtotalMinor,
    required this.currencyCode,
    required this.lineCount,
    required this.lines,
  });

  @override
  int get hashCode =>
      draftOrderId.hashCode ^
      fulfillment.hashCode ^
      draftState.hashCode ^
      tableName.hashCode ^
      kitchenNote.hashCode ^
      revision.hashCode ^
      subtotalMinor.hashCode ^
      currencyCode.hashCode ^
      lineCount.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityDraftOrderView &&
          runtimeType == other.runtimeType &&
          draftOrderId == other.draftOrderId &&
          fulfillment == other.fulfillment &&
          draftState == other.draftState &&
          tableName == other.tableName &&
          kitchenNote == other.kitchenNote &&
          revision == other.revision &&
          subtotalMinor == other.subtotalMinor &&
          currencyCode == other.currencyCode &&
          lineCount == other.lineCount &&
          lines == other.lines;
}

class CommunityExpenseView {
  final String expenseId;
  final String category;
  final String description;
  final PlatformInt64 amountMinor;
  final String currencyCode;
  final String paymentMethod;
  final String incurredAtUtc;

  const CommunityExpenseView({
    required this.expenseId,
    required this.category,
    required this.description,
    required this.amountMinor,
    required this.currencyCode,
    required this.paymentMethod,
    required this.incurredAtUtc,
  });

  @override
  int get hashCode =>
      expenseId.hashCode ^
      category.hashCode ^
      description.hashCode ^
      amountMinor.hashCode ^
      currencyCode.hashCode ^
      paymentMethod.hashCode ^
      incurredAtUtc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityExpenseView &&
          runtimeType == other.runtimeType &&
          expenseId == other.expenseId &&
          category == other.category &&
          description == other.description &&
          amountMinor == other.amountMinor &&
          currencyCode == other.currencyCode &&
          paymentMethod == other.paymentMethod &&
          incurredAtUtc == other.incurredAtUtc;
}

class CommunityExpensesWorkspace {
  final String storageStatus;
  final bool available;
  final String? currencyCode;
  final PlatformInt64 totalMinor;
  final List<CommunityExpenseView> expenses;

  const CommunityExpensesWorkspace({
    required this.storageStatus,
    required this.available,
    this.currencyCode,
    required this.totalMinor,
    required this.expenses,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      currencyCode.hashCode ^
      totalMinor.hashCode ^
      expenses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityExpensesWorkspace &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          currencyCode == other.currencyCode &&
          totalMinor == other.totalMinor &&
          expenses == other.expenses;
}

/// A deliberately narrow, in-memory Community financial export. It contains
/// only verified branch-level payment/refund/expense aggregates and is passed
/// to Flutter solely so the owner can select an explicit save destination.
/// No local plaintext file is created by Rust.
class CommunityFinancialCsvExport {
  final String storageStatus;
  final bool available;
  final Uint8List csvBytes;
  final PlatformInt64 recordCount;
  final PlatformInt64 byteLength;

  const CommunityFinancialCsvExport({
    required this.storageStatus,
    required this.available,
    required this.csvBytes,
    required this.recordCount,
    required this.byteLength,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      csvBytes.hashCode ^
      recordCount.hashCode ^
      byteLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityFinancialCsvExport &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          csvBytes == other.csvBytes &&
          recordCount == other.recordCount &&
          byteLength == other.byteLength;
}

/// A stock view derived only from immutable local ledger movements.
class CommunityInventoryItemView {
  final String productId;
  final String displayName;
  final bool tracked;
  final PlatformInt64 balance;
  final PlatformInt64? lowStockThreshold;
  final bool lowStock;

  const CommunityInventoryItemView({
    required this.productId,
    required this.displayName,
    required this.tracked,
    required this.balance,
    this.lowStockThreshold,
    required this.lowStock,
  });

  @override
  int get hashCode =>
      productId.hashCode ^
      displayName.hashCode ^
      tracked.hashCode ^
      balance.hashCode ^
      lowStockThreshold.hashCode ^
      lowStock.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInventoryItemView &&
          runtimeType == other.runtimeType &&
          productId == other.productId &&
          displayName == other.displayName &&
          tracked == other.tracked &&
          balance == other.balance &&
          lowStockThreshold == other.lowStockThreshold &&
          lowStock == other.lowStock;
}

class CommunityInventoryWorkspace {
  final String storageStatus;
  final bool available;
  final List<CommunityInventoryItemView> items;

  const CommunityInventoryWorkspace({
    required this.storageStatus,
    required this.available,
    required this.items,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^ available.hashCode ^ items.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInventoryWorkspace &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          items == other.items;
}

/// Receipt-safe detail projection loaded from immutable financial snapshots.
/// It deliberately contains no current catalogue, database, or credential
/// information.
class CommunityInvoiceDetail {
  final String storageStatus;
  final bool available;
  final String? invoiceId;
  final PlatformInt64? invoiceNumber;
  final String? fulfillment;
  final PlatformInt64? subtotalMinor;
  final PlatformInt64? discountMinor;
  final PlatformInt64? taxMinor;
  final PlatformInt64? totalMinor;
  final PlatformInt64? refundedMinor;
  final String? currencyCode;
  final String? finalizedAtUtc;
  final List<CommunityInvoiceLineView> lines;
  final List<CommunityInvoicePaymentView> payments;

  const CommunityInvoiceDetail({
    required this.storageStatus,
    required this.available,
    this.invoiceId,
    this.invoiceNumber,
    this.fulfillment,
    this.subtotalMinor,
    this.discountMinor,
    this.taxMinor,
    this.totalMinor,
    this.refundedMinor,
    this.currencyCode,
    this.finalizedAtUtc,
    required this.lines,
    required this.payments,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      invoiceId.hashCode ^
      invoiceNumber.hashCode ^
      fulfillment.hashCode ^
      subtotalMinor.hashCode ^
      discountMinor.hashCode ^
      taxMinor.hashCode ^
      totalMinor.hashCode ^
      refundedMinor.hashCode ^
      currencyCode.hashCode ^
      finalizedAtUtc.hashCode ^
      lines.hashCode ^
      payments.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInvoiceDetail &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          invoiceId == other.invoiceId &&
          invoiceNumber == other.invoiceNumber &&
          fulfillment == other.fulfillment &&
          subtotalMinor == other.subtotalMinor &&
          discountMinor == other.discountMinor &&
          taxMinor == other.taxMinor &&
          totalMinor == other.totalMinor &&
          refundedMinor == other.refundedMinor &&
          currencyCode == other.currencyCode &&
          finalizedAtUtc == other.finalizedAtUtc &&
          lines == other.lines &&
          payments == other.payments;
}

class CommunityInvoiceLineView {
  final String displayName;
  final List<String> modifierNames;
  final PlatformInt64 quantity;
  final PlatformInt64 unitPriceMinor;
  final PlatformInt64 lineTotalMinor;

  const CommunityInvoiceLineView({
    required this.displayName,
    required this.modifierNames,
    required this.quantity,
    required this.unitPriceMinor,
    required this.lineTotalMinor,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      modifierNames.hashCode ^
      quantity.hashCode ^
      unitPriceMinor.hashCode ^
      lineTotalMinor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInvoiceLineView &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          modifierNames == other.modifierNames &&
          quantity == other.quantity &&
          unitPriceMinor == other.unitPriceMinor &&
          lineTotalMinor == other.lineTotalMinor;
}

class CommunityInvoicePaymentView {
  final String paymentMethod;
  final PlatformInt64 amountMinor;

  const CommunityInvoicePaymentView({
    required this.paymentMethod,
    required this.amountMinor,
  });

  @override
  int get hashCode => paymentMethod.hashCode ^ amountMinor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInvoicePaymentView &&
          runtimeType == other.runtimeType &&
          paymentMethod == other.paymentMethod &&
          amountMinor == other.amountMinor;
}

class CommunityInvoiceView {
  final String invoiceId;
  final PlatformInt64 invoiceNumber;
  final PlatformInt64 totalMinor;
  final String currencyCode;
  final String finalizedAtUtc;
  final String paymentMethod;

  const CommunityInvoiceView({
    required this.invoiceId,
    required this.invoiceNumber,
    required this.totalMinor,
    required this.currencyCode,
    required this.finalizedAtUtc,
    required this.paymentMethod,
  });

  @override
  int get hashCode =>
      invoiceId.hashCode ^
      invoiceNumber.hashCode ^
      totalMinor.hashCode ^
      currencyCode.hashCode ^
      finalizedAtUtc.hashCode ^
      paymentMethod.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityInvoiceView &&
          runtimeType == other.runtimeType &&
          invoiceId == other.invoiceId &&
          invoiceNumber == other.invoiceNumber &&
          totalMinor == other.totalMinor &&
          currencyCode == other.currencyCode &&
          finalizedAtUtc == other.finalizedAtUtc &&
          paymentMethod == other.paymentMethod;
}

class CommunityItemSalesView {
  final String displayName;
  final PlatformInt64 quantity;
  final PlatformInt64 grossTotalMinor;
  final String currencyCode;

  const CommunityItemSalesView({
    required this.displayName,
    required this.quantity,
    required this.grossTotalMinor,
    required this.currencyCode,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^
      quantity.hashCode ^
      grossTotalMinor.hashCode ^
      currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityItemSalesView &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          quantity == other.quantity &&
          grossTotalMinor == other.grossTotalMinor &&
          currencyCode == other.currencyCode;
}

class CommunityKitchenTicketLineView {
  final String displayName;
  final List<String> modifierNames;
  final PlatformInt64 quantity;

  const CommunityKitchenTicketLineView({
    required this.displayName,
    required this.modifierNames,
    required this.quantity,
  });

  @override
  int get hashCode =>
      displayName.hashCode ^ modifierNames.hashCode ^ quantity.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityKitchenTicketLineView &&
          runtimeType == other.runtimeType &&
          displayName == other.displayName &&
          modifierNames == other.modifierNames &&
          quantity == other.quantity;
}

class CommunityKitchenTicketView {
  final String ticketId;
  final String? tableLabel;
  final String state;
  final PlatformInt64 revision;

  /// Kitchen receives only the stop-work signal. The counter's free-text
  /// rationale remains in the protected audit ledger.
  final bool cancellationPending;

  /// The immutable, counter-provided operational instruction for this
  /// ticket. Cancellation and management rationales never cross this
  /// boundary.
  final String? kitchenNote;
  final List<CommunityKitchenTicketLineView> lines;

  const CommunityKitchenTicketView({
    required this.ticketId,
    this.tableLabel,
    required this.state,
    required this.revision,
    required this.cancellationPending,
    this.kitchenNote,
    required this.lines,
  });

  @override
  int get hashCode =>
      ticketId.hashCode ^
      tableLabel.hashCode ^
      state.hashCode ^
      revision.hashCode ^
      cancellationPending.hashCode ^
      kitchenNote.hashCode ^
      lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityKitchenTicketView &&
          runtimeType == other.runtimeType &&
          ticketId == other.ticketId &&
          tableLabel == other.tableLabel &&
          state == other.state &&
          revision == other.revision &&
          cancellationPending == other.cancellationPending &&
          kitchenNote == other.kitchenNote &&
          lines == other.lines;
}

class CommunityModifierOptionView {
  final String modifierOptionId;
  final String displayName;
  final PlatformInt64 priceDeltaMinor;
  final String currencyCode;
  final PlatformInt64 revision;
  final bool archived;

  const CommunityModifierOptionView({
    required this.modifierOptionId,
    required this.displayName,
    required this.priceDeltaMinor,
    required this.currencyCode,
    required this.revision,
    required this.archived,
  });

  @override
  int get hashCode =>
      modifierOptionId.hashCode ^
      displayName.hashCode ^
      priceDeltaMinor.hashCode ^
      currencyCode.hashCode ^
      revision.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityModifierOptionView &&
          runtimeType == other.runtimeType &&
          modifierOptionId == other.modifierOptionId &&
          displayName == other.displayName &&
          priceDeltaMinor == other.priceDeltaMinor &&
          currencyCode == other.currencyCode &&
          revision == other.revision &&
          archived == other.archived;
}

class CommunityOpenCashDrawer {
  final String sessionId;
  final PlatformInt64 openingCashMinor;
  final String currencyCode;

  const CommunityOpenCashDrawer({
    required this.sessionId,
    required this.openingCashMinor,
    required this.currencyCode,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^ openingCashMinor.hashCode ^ currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityOpenCashDrawer &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          openingCashMinor == other.openingCashMinor &&
          currencyCode == other.currencyCode;
}

/// An untrusted tender selection. Rust validates its shape and compares the
/// final allocation sum to the trusted invoice total inside SQLCipher.
class CommunityPaymentAllocation {
  final String paymentMethod;
  final PlatformInt64 amountMinor;

  const CommunityPaymentAllocation({
    required this.paymentMethod,
    required this.amountMinor,
  });

  @override
  int get hashCode => paymentMethod.hashCode ^ amountMinor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityPaymentAllocation &&
          runtimeType == other.runtimeType &&
          paymentMethod == other.paymentMethod &&
          amountMinor == other.amountMinor;
}

class CommunityPortableBackupResult {
  final String storageStatus;
  final bool created;
  final String? backupFileName;
  final String? envelopeFileName;
  final String? sha256;

  const CommunityPortableBackupResult({
    required this.storageStatus,
    required this.created,
    this.backupFileName,
    this.envelopeFileName,
    this.sha256,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      created.hashCode ^
      backupFileName.hashCode ^
      envelopeFileName.hashCode ^
      sha256.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityPortableBackupResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          created == other.created &&
          backupFileName == other.backupFileName &&
          envelopeFileName == other.envelopeFileName &&
          sha256 == other.sha256;
}

class CommunityProductView {
  final String productId;
  final String? categoryId;
  final String displayName;
  final PlatformInt64 unitPriceMinor;
  final String currencyCode;
  final PlatformInt64 revision;
  final bool isAvailable;

  /// Provider-neutral tax treatment: `no_tax`, `exclusive`, or `inclusive`.
  final String taxTreatment;
  final String? imageAssetKey;
  final Uint8List? imageBytes;

  /// Retained product-bound options. Archived values are included solely so
  /// restored drafts and receipts can render historical selections; the
  /// POS selector filters them out before it submits a new sale.
  final List<CommunityModifierOptionView> modifierOptions;

  const CommunityProductView({
    required this.productId,
    this.categoryId,
    required this.displayName,
    required this.unitPriceMinor,
    required this.currencyCode,
    required this.revision,
    required this.isAvailable,
    required this.taxTreatment,
    this.imageAssetKey,
    this.imageBytes,
    required this.modifierOptions,
  });

  @override
  int get hashCode =>
      productId.hashCode ^
      categoryId.hashCode ^
      displayName.hashCode ^
      unitPriceMinor.hashCode ^
      currencyCode.hashCode ^
      revision.hashCode ^
      isAvailable.hashCode ^
      taxTreatment.hashCode ^
      imageAssetKey.hashCode ^
      imageBytes.hashCode ^
      modifierOptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityProductView &&
          runtimeType == other.runtimeType &&
          productId == other.productId &&
          categoryId == other.categoryId &&
          displayName == other.displayName &&
          unitPriceMinor == other.unitPriceMinor &&
          currencyCode == other.currencyCode &&
          revision == other.revision &&
          isAvailable == other.isAvailable &&
          taxTreatment == other.taxTreatment &&
          imageAssetKey == other.imageAssetKey &&
          imageBytes == other.imageBytes &&
          modifierOptions == other.modifierOptions;
}

class CommunityRestaurantProfileRegistry {
  final String storageStatus;
  final bool available;
  final String? edition;
  final String? deviceRole;
  final String? activeProfileId;
  final List<CommunityRestaurantProfileView> profiles;

  const CommunityRestaurantProfileRegistry({
    required this.storageStatus,
    required this.available,
    this.edition,
    this.deviceRole,
    this.activeProfileId,
    required this.profiles,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      edition.hashCode ^
      deviceRole.hashCode ^
      activeProfileId.hashCode ^
      profiles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityRestaurantProfileRegistry &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          edition == other.edition &&
          deviceRole == other.deviceRole &&
          activeProfileId == other.activeProfileId &&
          profiles == other.profiles;
}

class CommunityRestaurantProfileView {
  final String profileId;
  final String label;
  final String createdAtUtc;
  final bool isActive;

  const CommunityRestaurantProfileView({
    required this.profileId,
    required this.label,
    required this.createdAtUtc,
    required this.isActive,
  });

  @override
  int get hashCode =>
      profileId.hashCode ^
      label.hashCode ^
      createdAtUtc.hashCode ^
      isActive.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityRestaurantProfileView &&
          runtimeType == other.runtimeType &&
          profileId == other.profileId &&
          label == other.label &&
          createdAtUtc == other.createdAtUtc &&
          isActive == other.isActive;
}

class CommunitySalePricingPreview {
  final String storageStatus;
  final bool available;
  final PlatformInt64 subtotalMinor;
  final PlatformInt64 discountMinor;
  final PlatformInt64 taxMinor;
  final PlatformInt64 payableMinor;
  final String? currencyCode;

  const CommunitySalePricingPreview({
    required this.storageStatus,
    required this.available,
    required this.subtotalMinor,
    required this.discountMinor,
    required this.taxMinor,
    required this.payableMinor,
    this.currencyCode,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      subtotalMinor.hashCode ^
      discountMinor.hashCode ^
      taxMinor.hashCode ^
      payableMinor.hashCode ^
      currencyCode.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunitySalePricingPreview &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          subtotalMinor == other.subtotalMinor &&
          discountMinor == other.discountMinor &&
          taxMinor == other.taxMinor &&
          payableMinor == other.payableMinor &&
          currencyCode == other.currencyCode;
}

/// A deliberately small, user-safe checkout result. Detailed storage errors
/// and security-sensitive database state never cross the FFI boundary.
class CommunitySaleResult {
  final String storageStatus;
  final bool completed;
  final String? invoiceNumber;
  final PlatformInt64 totalMinor;
  final String? currencyCode;
  final String? paymentMethod;

  const CommunitySaleResult({
    required this.storageStatus,
    required this.completed,
    this.invoiceNumber,
    required this.totalMinor,
    this.currencyCode,
    this.paymentMethod,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      completed.hashCode ^
      invoiceNumber.hashCode ^
      totalMinor.hashCode ^
      currencyCode.hashCode ^
      paymentMethod.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunitySaleResult &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          completed == other.completed &&
          invoiceNumber == other.invoiceNumber &&
          totalMinor == other.totalMinor &&
          currencyCode == other.currencyCode &&
          paymentMethod == other.paymentMethod;
}

/// A local-only sales summary for one UTC accounting day. Values are
/// calculated by Rust from finalized financial records; Flutter never
/// aggregates or invents totals.
class CommunitySalesSummary {
  final String storageStatus;
  final bool available;
  final String? accountingDateUtc;
  final String? branchTimeZone;
  final PlatformInt64 invoiceCount;
  final PlatformInt64 totalMinor;
  final PlatformInt64 cashMinor;
  final PlatformInt64 cardMinor;
  final PlatformInt64 upiMinor;
  final PlatformInt64 refundMinor;
  final PlatformInt64 expenseMinor;
  final PlatformInt64 discountMinor;
  final PlatformInt64 taxMinor;
  final String? currencyCode;
  final PlatformInt64 schemaVersion;
  final PlatformInt64 auditEventCount;
  final bool dayClosed;
  final String? dayClosedAtUtc;
  final String? dayCloseReason;
  final List<CommunityInvoiceView> recentInvoices;
  final List<CommunityItemSalesView> topItems;

  const CommunitySalesSummary({
    required this.storageStatus,
    required this.available,
    this.accountingDateUtc,
    this.branchTimeZone,
    required this.invoiceCount,
    required this.totalMinor,
    required this.cashMinor,
    required this.cardMinor,
    required this.upiMinor,
    required this.refundMinor,
    required this.expenseMinor,
    required this.discountMinor,
    required this.taxMinor,
    this.currencyCode,
    required this.schemaVersion,
    required this.auditEventCount,
    required this.dayClosed,
    this.dayClosedAtUtc,
    this.dayCloseReason,
    required this.recentInvoices,
    required this.topItems,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      accountingDateUtc.hashCode ^
      branchTimeZone.hashCode ^
      invoiceCount.hashCode ^
      totalMinor.hashCode ^
      cashMinor.hashCode ^
      cardMinor.hashCode ^
      upiMinor.hashCode ^
      refundMinor.hashCode ^
      expenseMinor.hashCode ^
      discountMinor.hashCode ^
      taxMinor.hashCode ^
      currencyCode.hashCode ^
      schemaVersion.hashCode ^
      auditEventCount.hashCode ^
      dayClosed.hashCode ^
      dayClosedAtUtc.hashCode ^
      dayCloseReason.hashCode ^
      recentInvoices.hashCode ^
      topItems.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunitySalesSummary &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          accountingDateUtc == other.accountingDateUtc &&
          branchTimeZone == other.branchTimeZone &&
          invoiceCount == other.invoiceCount &&
          totalMinor == other.totalMinor &&
          cashMinor == other.cashMinor &&
          cardMinor == other.cardMinor &&
          upiMinor == other.upiMinor &&
          refundMinor == other.refundMinor &&
          expenseMinor == other.expenseMinor &&
          discountMinor == other.discountMinor &&
          taxMinor == other.taxMinor &&
          currencyCode == other.currencyCode &&
          schemaVersion == other.schemaVersion &&
          auditEventCount == other.auditEventCount &&
          dayClosed == other.dayClosed &&
          dayClosedAtUtc == other.dayClosedAtUtc &&
          dayCloseReason == other.dayCloseReason &&
          recentInvoices == other.recentInvoices &&
          topItems == other.topItems;
}

class CommunityStaffSecurity {
  final String storageStatus;
  final bool available;
  final bool ownerPinSetupRequired;
  final String? activeStaffId;
  final String? activeStaffName;
  final String? activeStaffRole;
  final List<CommunityStaffView> staff;

  const CommunityStaffSecurity({
    required this.storageStatus,
    required this.available,
    required this.ownerPinSetupRequired,
    this.activeStaffId,
    this.activeStaffName,
    this.activeStaffRole,
    required this.staff,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      ownerPinSetupRequired.hashCode ^
      activeStaffId.hashCode ^
      activeStaffName.hashCode ^
      activeStaffRole.hashCode ^
      staff.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityStaffSecurity &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          ownerPinSetupRequired == other.ownerPinSetupRequired &&
          activeStaffId == other.activeStaffId &&
          activeStaffName == other.activeStaffName &&
          activeStaffRole == other.activeStaffRole &&
          staff == other.staff;
}

/// A narrow local-auth projection for the Flutter lock screen. It contains no
/// PIN digest, session timestamp, or authentication-attempt history.
class CommunityStaffView {
  final String staffId;
  final String displayName;
  final String role;
  final bool active;
  final bool pinConfigured;

  const CommunityStaffView({
    required this.staffId,
    required this.displayName,
    required this.role,
    required this.active,
    required this.pinConfigured,
  });

  @override
  int get hashCode =>
      staffId.hashCode ^
      displayName.hashCode ^
      role.hashCode ^
      active.hashCode ^
      pinConfigured.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityStaffView &&
          runtimeType == other.runtimeType &&
          staffId == other.staffId &&
          displayName == other.displayName &&
          role == other.role &&
          active == other.active &&
          pinConfigured == other.pinConfigured;
}

/// Owner-only local sync-queue view. It intentionally excludes payloads,
/// hashes, device identifiers, actor identifiers, and correlation material.
class CommunitySyncQueue {
  final String storageStatus;
  final bool available;
  final PlatformInt64 pendingCount;
  final List<CommunitySyncQueueItemView> operations;

  const CommunitySyncQueue({
    required this.storageStatus,
    required this.available,
    required this.pendingCount,
    required this.operations,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      available.hashCode ^
      pendingCount.hashCode ^
      operations.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunitySyncQueue &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          pendingCount == other.pendingCount &&
          operations == other.operations;
}

class CommunitySyncQueueItemView {
  final PlatformInt64 sequence;
  final String eventType;
  final String entityType;
  final String createdAtUtc;

  const CommunitySyncQueueItemView({
    required this.sequence,
    required this.eventType,
    required this.entityType,
    required this.createdAtUtc,
  });

  @override
  int get hashCode =>
      sequence.hashCode ^
      eventType.hashCode ^
      entityType.hashCode ^
      createdAtUtc.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunitySyncQueueItemView &&
          runtimeType == other.runtimeType &&
          sequence == other.sequence &&
          eventType == other.eventType &&
          entityType == other.entityType &&
          createdAtUtc == other.createdAtUtc;
}

class CommunityTaxRateView {
  final String taxRateId;
  final String displayName;
  final PlatformInt64 basisPoints;
  final PlatformInt64 revision;
  final bool archived;

  const CommunityTaxRateView({
    required this.taxRateId,
    required this.displayName,
    required this.basisPoints,
    required this.revision,
    required this.archived,
  });

  @override
  int get hashCode =>
      taxRateId.hashCode ^
      displayName.hashCode ^
      basisPoints.hashCode ^
      revision.hashCode ^
      archived.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityTaxRateView &&
          runtimeType == other.runtimeType &&
          taxRateId == other.taxRateId &&
          displayName == other.displayName &&
          basisPoints == other.basisPoints &&
          revision == other.revision &&
          archived == other.archived;
}

class CommunityTaxRateWorkspace {
  final String storageStatus;
  final bool available;
  final List<CommunityTaxRateView> rates;

  const CommunityTaxRateWorkspace({
    required this.storageStatus,
    required this.available,
    required this.rates,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^ available.hashCode ^ rates.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityTaxRateWorkspace &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          available == other.available &&
          rates == other.rates;
}

class CommunityWorkspace {
  final String storageStatus;
  final bool setupRequired;
  final String? branchName;
  final List<CommunityCategoryView> categories;
  final List<CommunityProductView> products;
  final List<CommunityCustomerView> customers;
  final List<CommunityDraftOrderView> openDrafts;
  final List<CommunityKitchenTicketView> kitchenTickets;

  const CommunityWorkspace({
    required this.storageStatus,
    required this.setupRequired,
    this.branchName,
    required this.categories,
    required this.products,
    required this.customers,
    required this.openDrafts,
    required this.kitchenTickets,
  });

  @override
  int get hashCode =>
      storageStatus.hashCode ^
      setupRequired.hashCode ^
      branchName.hashCode ^
      categories.hashCode ^
      products.hashCode ^
      customers.hashCode ^
      openDrafts.hashCode ^
      kitchenTickets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommunityWorkspace &&
          runtimeType == other.runtimeType &&
          storageStatus == other.storageStatus &&
          setupRequired == other.setupRequired &&
          branchName == other.branchName &&
          categories == other.categories &&
          products == other.products &&
          customers == other.customers &&
          openDrafts == other.openDrafts &&
          kitchenTickets == other.kitchenTickets;
}

/// Untrusted catalogue selection supplied by Flutter. Rust verifies the
/// original bytes and every bounded provenance field before normalizing the
/// image or opening a storage transaction.
class GotiginCatalogMenuImageSelection {
  final String catalogImageId;
  final Uint8List originalImageBytes;
  final String contentSha256;
  final String licenceLabel;
  final String licenceUrl;
  final String serviceOrigin;
  final PlatformInt64 serviceSchemaVersion;

  const GotiginCatalogMenuImageSelection({
    required this.catalogImageId,
    required this.originalImageBytes,
    required this.contentSha256,
    required this.licenceLabel,
    required this.licenceUrl,
    required this.serviceOrigin,
    required this.serviceSchemaVersion,
  });

  @override
  int get hashCode =>
      catalogImageId.hashCode ^
      originalImageBytes.hashCode ^
      contentSha256.hashCode ^
      licenceLabel.hashCode ^
      licenceUrl.hashCode ^
      serviceOrigin.hashCode ^
      serviceSchemaVersion.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GotiginCatalogMenuImageSelection &&
          runtimeType == other.runtimeType &&
          catalogImageId == other.catalogImageId &&
          originalImageBytes == other.originalImageBytes &&
          contentSha256 == other.contentSha256 &&
          licenceLabel == other.licenceLabel &&
          licenceUrl == other.licenceUrl &&
          serviceOrigin == other.serviceOrigin &&
          serviceSchemaVersion == other.serviceSchemaVersion;
}
